import streamlit as st
import pandas as pd
import random

# 1. ตั้งค่าหน้าเว็บ
st.set_page_config(
    page_title="Lucky Number Coupons",
    page_icon="💎",
    layout="wide"
)

# 2. ฟังก์ชันสร้างข้อมูลเลขตอง (11111 - 99999)
def generate_lucky_coupons():
    coupons = []
    # ลูปเลข 1 ถึง 9
    for i in range(1, 10):
        # สร้างเลขตอง 5 หลัก โดยแปลงเลขเป็น string แล้วคูณ 5 (เช่น "1"*5 = "11111")
        code = str(i) * 5 
        
        # จำลองข้อมูลอื่นๆ ประกอบให้เหมือนจริง
        item = {
            "Coupon ID": f"VIP-{code}",
            "Code (เลขตอง)": code,
            "Value (มูลค่า)": 1000, # สมมติมูลค่า
            "Status": random.choice(["Available", "Used", "Reserved"]), # สุ่มสถานะ
            "Type": "Platinum"
        }
        coupons.append(item)
    
    return pd.DataFrame(coupons)

# 3. ส่วนแสดงผลหลัก (Main Interface)
st.title("💎 ระบบจัดการคูปองเลขสวย (VIP Lucky Numbers)")
st.markdown("ชุดข้อมูลเลขตอง **11111 - 99999**")
st.markdown("---")

# สร้าง Sidebar สำหรับ Filter
st.sidebar.header("🔍 ตัวเลือกการกรอง")
status_filter = st.sidebar.multiselect(
    "เลือกสถานะคูปอง",
    options=["Available", "Used", "Reserved"],
    default=["Available", "Used", "Reserved"]
)

# โหลดข้อมูล
df = generate_lucky_coupons()

# 4. การกรองข้อมูล (Filter Logic)
if status_filter:
    df_show = df[df["Status"].isin(status_filter)]
else:
    df_show = df # ถ้าไม่เลือกอะไรเลย ให้แสดงทั้งหมด

# 5. แสดงผล Metric (สรุปตัวเลข)
c1, c2, c3 = st.columns(3)

with c1:
    st.metric("จำนวนคูปองทั้งหมด", f"{len(df)} ใบ")

with c2:
    st.metric("จำนวนที่แสดงผล", f"{len(df_show)} ใบ")

with c3:
    # คำนวณมูลค่ารวมของคูปองที่แสดงอยู่
    total_val = df_show["Value (มูลค่า)"].sum()
    st.metric("มูลค่ารวม (บาท)", f"{total_val:,}")

st.markdown("### 📋 ตารางรายชื่อคูปอง")

# 6. แสดงตารางข้อมูล
# ใช้ st.data_editor เพื่อให้ดูสวยและแก้ไขเล่นได้ (แต่ไม่ได้เซฟจริง)
st.data_editor(
    df_show,
    column_config={
        "Status": st.column_config.SelectboxColumn(
            "สถานะ",
            options=["Available", "Used", "Reserved"],
            width="medium",
            required=True,
        ),
        "Value (มูลค่า)": st.column_config.NumberColumn(
            "มูลค่า (บาท)",
            format="%d ฿"
        ),
        "Code (เลขตอง)": st.column_config.TextColumn(
            "รหัสคูปอง",
            help="เลขตอง 5 หลัก",
        )
    },
    hide_index=True,
    use_container_width=True
)

# 7. ปุ่มดาวน์โหลดข้อมูล (Optional)
# เพื่อนำข้อมูลชุดนี้ไปใช้ต่อ หรือเอาไป Import เข้า Firebase จริงๆ
csv = df_show.to_csv(index=False).encode('utf-8')
st.download_button(
    label="📥 ดาวน์โหลดข้อมูลเป็น CSV",
    data=csv,
    file_name="lucky_coupons_11111_99999.csv",
    mime="text/csv",
)

# Footer
st.markdown("---")
st.caption("Auto-generated by Smart Washer System | 11111-99999 Series")
